micronaut:
  application:
    name: iot-starter
  server:
    port: 8201
netty:
  default:
    allocator:
      max-order: 3

azure:
  hubHost   : "blumtest-iot.azure-devices.net"
  connection: "use an application-local.yml where you add this value; use the local profile then"

crypto:
  outputFolder: ""
  ellipticCurve: "prime256v1"
  expirationYear: 2050
